[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.3"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell", "msi"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = [
    "aarch64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = true
# This setting determines to what extent we run your Release CI on pull-requests
pr-run-mode = "plan" # "skip" | "plan" | "upload"
# Whether to enable GitHub Attestations
github-attestations = true
# Additional steps to run when building release binaries
github-build-setup = "../dist/remove-workspace-hack.yml"
# Dynamically link the C runtime on Windows builds
msvc-crt-static = false

[dist.github-custom-runners]
x86_64-pc-windows-msvc = "windows-latest"
x86_64-unknown-linux-gnu = "ubuntu-latest"
aarch64-unknown-linux-gnu = "ubuntu-latest"
global = "ubuntu-latest"

[dist.dependencies.apt]
libasound2-dev = "*"
pkg-config = "*"
wget = "*"
libavutil-dev = "*"
libavformat-dev = "*"
protobuf-compiler = "*"

[dist.dependencies.homebrew]
protobuf = "*"

[dist.dependencies.chocolatey]
protoc = "*"
